spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/temporal_rift
    username: temporal_rift
    password: temporal_rift
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT

logging:
  level:
    io.github.temporalrift: DEBUG
