spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/temporal_rift
    username: ${SPRING_DATASOURCE_USERNAME:temporal_rift}
    password: ${SPRING_DATASOURCE_PASSWORD:temporal_rift}
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT

logging:
  level:
    io.github.temporalrift: DEBUG
